on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  Build:
    runs-on: ubuntu-22.04
    container: saschpe/android-sdk:34-jdk22.0.1_8
    steps:
      - name: Install Node.js (for Actions)
        run: apt-get update && apt-get install -yqq node.js

      - uses: actions/checkout@v4
      - name: Build APK
        run: ./gradlew build
